services:
  postgres:
    container_name: ms_postgresql
    image: postgres
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
        PGDATA: /var/lib/postgresql/data
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - microservices-network
    restart: unless-stopped

  mongodb:
    container_name: ms_mongodb
    image: mongo
    volumes:
        - mongodb:/data
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - microservices-network

  mongo-express:
    container_name: ms_mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
    restart: unless-stopped
    networks:
        - microservices-network

  mail-dev:
    container_name: ms_mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    ports:
      - '5672:5672'    # AMQP port
      - '15672:15672'  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
        - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres:
  mongodb:
  rabbitmq_data: